/**
 * Copyright (c) 2024-2025 Stone Rhino and contributors.
 *
 * MIT License (http://opensource.org/licenses/MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
#pragma once

#include "args.h"
#include "args_combined_size.h"
#include "args_get.h"
#include "args_get_names.h"
#include "args_names.h"
#include "args_post.h"
#include "args_post_names.h"
#include "auth_type.h"
#include "duration.h"
#include "env.h"
#include "files.h"
#include "files_combined_size.h"
#include "files_names.h"
#include "files_sizes.h"
#include "files_tmp_content.h"
#include "files_tmpnames.h"
#include "full_request.h"
#include "full_request_length.h"
#include "geo.h"
#include "highest_severity.h"
#include "inbound_data_error.h"
#include "matched_var.h"
#include "matched_var_name.h"
#include "matched_vars.h"
#include "matched_vars_names.h"
#include "modsec_build.h"
#include "msc_pcre_limits_exceeded.h"
#include "multipart_boundary_quoted.h"
#include "multipart_boundary_whitespace.h"
#include "multipart_crlf_lf_lines.h"
#include "multipart_data_after.h"
#include "multipart_data_before.h"
#include "multipart_file_limit_exceeded.h"
#include "multipart_filename.h"
#include "multipart_header_folding.h"
#include "multipart_invalid_header_folding.h"
#include "multipart_invalid_part.h"
#include "multipart_invalid_quoting.h"
#include "multipart_lf_line.h"
#include "multipart_missing_semicolon.h"
#include "multipart_name.h"
#include "multipart_part_headers.h"
#include "multipart_strict_error.h"
#include "multipart_unmatched_boundary.h"
#include "outbound_data_error.h"
#include "path_info.h"
#include "query_string.h"
#include "remote_addr.h"
#include "remote_host.h"
#include "remote_port.h"
#include "remote_user.h"
#include "reqbody_error.h"
#include "reqbody_error_msg.h"
#include "reqbody_processor.h"
#include "reqbody_processor_error.h"
#include "request_basename.h"
#include "request_body.h"
#include "request_body_length.h"
#include "request_cookies.h"
#include "request_cookies_names.h"
#include "request_filename.h"
#include "request_headers.h"
#include "request_headers_names.h"
#include "request_line.h"
#include "request_method.h"
#include "request_protocol.h"
#include "request_uri.h"
#include "request_uri_raw.h"
#include "response_body.h"
#include "response_content_length.h"
#include "response_content_type.h"
#include "response_headers.h"
#include "response_headers_names.h"
#include "response_protocol.h"
#include "response_status.h"
#include "rule.h"
#include "server_addr.h"
#include "server_name.h"
#include "server_port.h"
#include "session.h"
#include "sessionid.h"
#include "status_line.h"
#include "time.h"
#include "time_day.h"
#include "time_epoch.h"
#include "time_hour.h"
#include "time_min.h"
#include "time_mon.h"
#include "time_sec.h"
#include "time_wday.h"
#include "time_year.h"
#include "tx.h"
#include "unique_id.h"
#include "urlencoded_error.h"
#include "userid.h"
#include "webappid.h"
#include "xml.h"